---
- name: restart ksql
  systemd:
    daemon_reload: true
    name: "{{ksql_service_name}}"
    state: restarted
  when:
    - skip_restart_handlers | default("false") == "false"
  tags:
    - systemd
