---
- name: restart control center
  systemd:
    daemon_reload: true
    name: "{{control_center_service_name}}"
    state: restarted
    when:
      - skip_restart_handlers | default("false") == "false"
  tags:
    - systemd
